# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 大道至简
email: liuyaqiu1993@gmail.com
description: This is just my test blog on my local host. I learn jekyll by this test blog. Jekyll is a simple and good blog ware!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: liuyaqiu93
github_username: liuyaqiu

permalink: /:title
# Build settings
markdown: kramdown
